### ISSUE TITLE
Madgraph 2.5.x open issues

### ISSUE THREAD

**Issue by bendavid** [cms-sw/genproductions#1200]
- [x] we need to move to either 2.5.6 once it's available, or else 2.5.5 plus one additional patch affecting Vgamma type processes at NLO

- [x] LO systematic weights can now be handled directly by madgraph, such that syscalc is no longer needed.  We should remove it completely from the scripts and make sure the built in functionality is working correctly (consistent order of weights between LO and NLO, reasonable naming of weights in header, reasonable value/behaviour for weights)

- [ ] once condor at CERN is working correctly (without relying on either afs or Eos) we can also deprecate lsf support and related patches.

- [ ] add example for LO weight biasing (SUSY group has started looking at this)

**Comment by qliphy** [comment]
@bendavid 
About point 1,  it seems 2.5.5 has already fixed the bug for Vgamma? See e.g. in [1]
And from MG Launchpad, the latest 25 release is 255 [2].  So shall we wait for 256 or go with 255?

[1] https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4041.html
[2] https://launchpad.net/mg5amcnlo

**Comment by bendavid** [comment]
There is an additional fix here
http://bazaar.launchpad.net/~mg5core1/mg5amcnlo/2.5.6/revision/276

So we either need to add this as an additional path on top of 2.5.5, or wait for 2.5.6

**Comment by kdlong** [comment]
@bendavid as for deprecating LSF use at CERN, do you know what the time scale for LSF to be deprecated by computing? Since we continue to see issues with condor at lxplus, its maybe overly optimistic to expect us to not rely on LSF at all for the coming production (unless we have no choice). However, I think CMSConnect should be ready for large scale production and is a better solution than condor at lxplus in any case.

@qliphy, @vciulli : I understood that @govoni would push for us to implement this patch on top of the MG2.5.5 and start testing now rather than waiting for 2.5.6. I know your group is very interested in these samples. Do you have someone that could implement the patch and test? Maybe @menglu21? In addition I can contact some of the other people in SMP-VV who have expressed interest in having these samples quickly.

**Comment by qliphy** [comment]
@kdlong Me and Meng can start looking at that, for e.g. W01234Jets MLM and ZGamma+Jets.  We will let you know.

**Comment by perrozzi** [comment]
@kdlong I think that LSF will be deprecated in a couple of years from now, for the moment we have less resources than in the past but we can (and want) certainly to continue using it

**Comment by bendavid** [comment]
Well, maintaining support for it in madgraph is quite some work, so I would say we don't need it anymore once condor at lxplus is working and well tested.

**Comment by perrozzi** [comment]
is this completed or anything still open?

**Comment by perrozzi** [comment]
closing this, further discussion will happen here https://github.com/cms-sw/genproductions/issues/1290
