### ISSUE TITLE
MadGraph LO ttZ sample includes ttG and ttH (to leptons)

### ISSUE THREAD

**Issue by dpgilbert** [cms-sw/genproductions#1244]
The process lines here:

https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/13TeV/TTZJets/TTZJets_5f_LO_MLM/ttZ01j_5f_proc_card.dat#L10

and here:

https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/13TeV/TTZJets/TTZJets_5f_LO_MLM/ttZ01j_5f_proc_card.dat#L13

should force Z production using t t~ z, z > ell+ ell- syntax. As written, gamma and higgs production is included in the sample.

The NLO proc card excludes higgs but not photons. The same issue may be present there as well.

**Comment by bendavid** [comment]
I believe the inclusion of photons was intentional in current samples.

Since the Z and photon both couple to the top with otherwise identical topologies, there is in principle Z/gamma* interference like in inclusive drell-yan production, and in practice one has a continuum spectrum for dilepton mass below the Z peak which is relevant phase space for some analyses.

Agreed that the Higgs should be excluded (depending on how the coupling orders work out there could indeed be some H->tau tau contribution).  But this should be done with the " / h" syntax to exclude the higgs, rather than explicitly forcing the Z.

**Comment by dpgilbert** [comment]
Could you explain what makes forcing Z production in e.g. line 8 acceptable, but not in line 10? I believe you regarding the Z/gamma* issue, but then shouldn't that be an issue everywhere gamma* could appear?

**Comment by bendavid** [comment]
For the neutrino case there is no photon contribution of course.

For the quark case, in principle there is a gamma* contribution, however including it would screw up the jet matching, because then jets from the production and decay cannot be clearly separated any more.  In practice the off-shell contribution is considered less relevant for the jets, since that phase space is dominated by tt+2 jets.

**Comment by perrozzi** [comment]
I believe this issue is solved, closing it.
Please reopen in case is still needed
