### ISSUE TITLE
Update POWHEG scripts to include all recommended 2017 PDFs

### ISSUE THREAD

**Issue by kdlong** [cms-sw/genproductions#1251]
Update POWHEG scripts to include weights for all PDF sets recommended for 2017. The list can be seen in [1]. The lines in [2] should be modified to call the full list of LHAPDF set numbers. Since the list is quite long, I would strongly recommend defining a function which takes in the central set ID and number of entries rather than coping the code 30 times.

@covarell @yuanchao have you started to look at this yet? Do you think it can be addressed in a short time scale?

[1] https://docs.google.com/spreadsheets/d/1YjhruLPvmwqoA1YZPgmU5H9T3ELnYnriHgO9DrJQoxk/edit#gid=0
[2] https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/runcmsgrid_powheg.sh#L193-L366

**Comment by covarell** [comment]
Yes. But we are in the middle of a massive powheg migration to the new reweighting scheme (absolutely necessary because the old-styled powheg will never work with o(1k) weights). In this scheme, all the reweighting lines are dropped from the .sh and stored in a special list parsed by powheg itself.

See:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/PowhegBOXPrecompiled#Download_all_the_necessary_s_AN1

@perrozzi prepared a test branch for us. I am planning to test it this week, then we can prepare the long list and make a PR. Then MC contacts will need to test processes one by one, because in fact noone ever tested powheg with 1k weights (when I told Paolo Nason he thought I was joking...)

**Comment by perrozzi** [comment]
@covarell I assume this can be closed, let me know otherwise
