### ISSUE TITLE
[2017 MC v2] Finalize pdf weights for 2017

### ISSUE THREAD

**Issue by bendavid** [cms-sw/genproductions#1287]
These would be useful for alpha_s extraction studies.

Pdf sets are 

322500 | NNPDF31_nnlo_as_0108
322700 | NNPDF31_nnlo_as_0110
322900 | NNPDF31_nnlo_as_0112
323100 | NNPDF31_nnlo_as_0114
323300 | NNPDF31_nnlo_as_0117
323500 | NNPDF31_nnlo_as_0119
323700 | NNPDF31_nnlo_as_0122
323900 | NNPDF31_nnlo_as_0124

Each includes full uncertainties (101 replicas) but it would be sufficient to just have the central set for each (ie 8 additional weights)

**Comment by efeyazgan** [comment]
Would this be a template analysis?
Won't you consider using a Fixed Order calculation (e.g. analogous to TOP-17-001)?

**Comment by bendavid** [comment]
This is a general request for the moment to leave open the possibility of doing something at detector level also.
(since it's only 8 additional weights the cost is not so high)

**Comment by syuvivida** [comment]
Hello,
  Could we add the following two PDF sets in the list of PDF weights? I think just the central values are OK.
263000    NNPDF30_lo_as_0130          --> to compare with ATLAS DM cross sections
263400    NNPDF30_lo_as_0130_nf_4 --> to cross check/compare with 2015/2016 MC samples

If possible, it would be nice to add these two PDF sets in the default runcmsgrid_LO.sh. If we can only add them for a subset of the samples, below is the list of samples to add:

               ZprimeToA0hToA0chichih*_2HDM_MZp-*_MA0-*_13TeV-madgraph*
               ZprimeToZhToZinvh*_2HDM_M-*_13TeV-madgraph
               MonoH*_ZpBaryonic_MZp-*_MChi-*_13TeV-madgraph
               MonoH*_Scalar_MZp-*_MChi-*_13TeV-madgraph
               ZprimeToWW*_narrow_M-*_13TeV-madgraph
               ZprimeToWW*_width*_M-*_13TeV-madgraph
               ZprimeToZH*_narrow_M-*13TeV-madgraph-pythia8
               ZprimeToZh*_narrow_M-*_13TeV-madgraph
               WprimeToWhToWlephtata_narrow_M-*_13TeV-madgraph
               WprimeToWZ_width*_M-*_TuneCUETP8M1_13TeV-madgraph-pythia8
               WprimeToWZ*_narrow_M-*_13TeV-madgraph
               BulkGravTohh*_narrow_M-*_13TeV-madgraph
               BulkGravToZZ*_narrow_M-*_TuneCUETP8M1_13TeV-madgraph-pythia8
               BulkGravToWW*_narrow_M-*_TuneCUETP8M1_13TeV-madgraph-pythia8
               RadionTohh*_narrow_M-4500_13TeV-madgraph
               Radion_hh_*_inclusive_narrow_M*_TuneCUETP8M1_13TeV-madgraph-pythia8
               RadionToWW*_narrow_M-*_13TeV-madgraph
               RadionToZZ*_narrow_M-*_13TeV-madgraph
               RadionToWW*_width*_M-*_13TeV-madgraph
               RadionToZZ*_width*_M-*_13TeV-madgraph               
               GluGluToRadionToHH*_M-*_narrow_13TeV-madgraph
               GluGluToBulkGraviton*_M-*_narrow_13TeV-madgraph

**Comment by perrozzi** [comment]
Current status is not yet coherent between mg5_amc (https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L471) and powheg (https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/make_rwl.py#L29)
summarized briefly in
[pdf_mg5_powheg.xlsx](https://github.com/cms-sw/genproductions/files/1283066/pdf_mg5_powheg.xlsx)

Concerning mg5_amc: 
- it would probably be a good idea to store the PDF variations of 292200 which was the default set used for 2016 MC, to keep back-compatibility in case is needed
- Also, why do we store 303600 (NNPDF31_nnlo_as_0118 ) and not 304400, i.e. the Hessian variations?!?
but we store instead 305800 (NNPDF31_nlo_hessian_pdfas) with variations?
- Why do we store 42400 (NNLO 3-flavour PDFs for the ABMP15 set) with replicas?!?

Concerning powheg: 
- a few central values missing (e.g. 305800 NNPDF31_nlo_hessian_pdfas)
- 315000 (NNPDF31_lo_as_0118) missing

**Comment by klipka** [comment]
We should store 305800 ( NNPDF31_nlo_hessian_pdfas ) and 306000 (NNPDF31_nnlo_hessian_pdfas )
There was apparently a typo in a number (303600 instead of 306000). These variations also include alpha_s. 

The set 42400 was not recommended (see PDF@CMS TWIKI), we recommend 42560 (using internal ABMP16 alpha_s) and 42780 (using 0.118) 

For LO tunes, I suggested 42500 (3-flavour fixed order PDF which might be appropriate for UE) but this was only a suggestion.


304200 ( NNPDF31_nlo_as_0118_hessian) and 304400 (NNPDF31_nnlo_as_0118_hessian).

**Comment by kdlong** [comment]
For the Hessian vs. MC set, it looks like the mistake is in the scripts, which has a mis-copy from the spreadsheet [1]. The scripts use 303600 (NNPDF31_nnlo_as_0118) when they should use 306000 (NNPDF31_nnlo_hessian_pdfas)

[1] https://docs.google.com/spreadsheets/d/1YjhruLPvmwqoA1YZPgmU5H9T3ELnYnriHgO9DrJQoxk/edit#gid=0

**Comment by klipka** [comment]
Hi Ken, indeed, I just answered to Luca’s comment in the gitHub.
thanks,
Katerina

**Comment by perrozzi** [comment]
Ciao, I would remove 42500 because is 3F.
Ken can you prepare a PR with the rest please?

**Comment by klipka** [comment]
Hi, yes 42500 3F can be removed.
cheers,
katerina

**Comment by perrozzi** [comment]
Modifications in https://github.com/cms-sw/genproductions/pull/1306:

   * Added NNPDF31_nnlo_as_ replicas (cfr https://github.com/cms-sw/genproductions/issues/1287#issue-250331575)
   * Added NNPDF30_nlo_nf_5_pdfas variations (for LO and NLO, both MG5_aMC and POWHEG) and NNPDF30_lo_as_0130 variations (for MG5_aMC LO) (cfr https://github.com/cms-sw/genproductions/issues/1287#issuecomment-323726819)
   * Replaced 303600 (NNPDF31_nnlo_as_0118) with 306000 (NNPDF31_nnlo_hessian_pdfas) (cfr https://github.com/cms-sw/genproductions/issues/1287#issuecomment-327743154)
   * Removed 42400 (ABMP15_3_nnlo), 
   * Remove 42780 (ABMP16als118_5_nnlo) replicas
   * Fixed a bug for HERAPDF20_NNLO_VAR in MG5_aMC LO
   * Restore NNPDF31_lo_as_0118 central value in POWHEG

Updated list for MG5_aMC LO and NLO, and POWHEG here: [pdf_mg5_powheg.xlsx](https://github.com/cms-sw/genproductions/files/1291145/pdf_mg5_powheg.xlsx)

**Still to do: MAKE AN "IF" TO USE 4F FLAVOR PDF (both central values and replicas) IN CASE THE IMPORTE MODEL IS 4F IN MG5_aMC@NLO. AT THE MOMENT I BELIEVE THINGS ARE NOT CONSISTENT. THIS IS VERY URGENT**

**Comment by klipka** [comment]
Hi Luca,

what is the reason for removing the ABMP16nnlo with as=0.118?

**Comment by perrozzi** [comment]
Hi Katerina, I kept the central value and removed the variations to re-introduce the NNPDF30_nlo_nf_5_pdfas variations that were used in 2016 and from several discussions are important to have.
May I ask what is the use case for ABMP16nnlo, apart comparing the central value?

**Comment by klipka** [comment]
Hi Luca, 

do you mean ABMP16nnlo or ABMPnnlo (as=0.118)? 

 ABMP16nnlo is the best theoretically treated PDF on the market, we need to have it with its uncertainties. It is often used in an incorrect way (with wot alpha_s or with wrong quark masses) therefore there is some care needed. To compare the uncertainty and central value, we need all the eigenvectors - and it is really not many !!! The version of ABMP16 with as=0.118 is also provided and I would like to have it for CMS analyses. See, the MMHT, NNPDF and CT have agreed value of as=0.118 which is about, but not exactly result of their own fit. ABMP was always puristic and provided PDFs only at their fitted alpha_s, which was smaller (and is e.g. in perfect agreement with our NNLO top results!). To be treated in a same way as CT, NN and MMHT, they provided now alps 0.118 version. We should include it as well. This is to my opinion much more important than the alpha_s variations from NNPSF3.1.

cheers,
Katerina

**Comment by perrozzi** [comment]
CMSSW_9_3_0 (to be used for POWHEG) contains the updated LHAPDF version and newest PDF sets. The script can be reverted to have all the sets.
For MG5_aMC@NLO we need to wait for https://github.com/cms-sw/cmsdist/pull/3417 to be merged and a new CMSSW_7_1_X release

**Comment by bendavid** [comment]
As discussed today, would like to keep the central value+hessian variations for the nominal 5fs pdf also in the case of 4fs samples.

**Comment by perrozzi** [comment]
cfr https://github.com/cms-sw/genproductions/pull/1328

**Comment by perrozzi** [comment]
CMSSW_7_1_30 out, I tested POWHEG and no dataset is missing, updated also MG5_aMC@NLO.
https://github.com/cms-sw/genproductions/pull/1328 merged, gridpacks ready to run!

**Comment by perrozzi** [comment]
We need to remove 7 PDF sets for MG5_aMC@NLO in NLO mode for 5F, as we are passing 37 entries and there is a limit to 30.
cfr https://github.com/cms-sw/genproductions/issues/1333
I don't think it matters whether we require only the central value or the full set.
In case, I propose to remove, for instance: 
13200, 'CT14lo'
25000, 'MMHT2014lo68cl'
315000, 'NNPDF31_lo_as_0118'
315200, 'NNPDF31_lo_as_0130'
262000, 'NNPDF30_lo_as_0118'
13163, 'CT14nlo_as_0116'
13167, 'CT14nlo_as_0120'

Another option is to ask the authors, find the reason for this limit, remove it in case there is no real reason.

**Comment by klipka** [comment]
For the NLO mode we dont need to keep LO sets. Do we still have this limit of 30 weights? In this case we can't keep the consistent error set for any pdf except for ABMP16, which has 30 error eigenvectors, or  - I cant believe me proposing this - PDF4LHC15_nlo_30_pdfas (set 90400).

**Comment by kdlong** [comment]
90400 is already included, right? I would say that it needs to be, as I think this is the set favored by the nanoAOD group.

**Comment by perrozzi** [comment]
@klipka I prefer to keep exactly the same pdf and replicas for all the sets, @kdlong made a pr to allow >30 sets.
@kdlong I didn't hear complaints about 100 pdf replicas to be too much, and being only one needing to serve potentially all the analysis, 100 should be better. opened an issue
https://github.com/cms-nanoAOD/cmssw/issues/14

**Comment by klipka** [comment]
yes we have 90400 in the list for all MC, but  - did I understood correctly that we have place only for 30 weights??

**Comment by kdlong** [comment]
The limit was actually on 30 sets, independent of the number of members in the sets. It's an arbitrary limit, originally it was 10 in MadGraph. I increased it to 40.

**Comment by klipka** [comment]
ok, but if the limit is 30, we should have one set with its uncertainties - so that we can calculate the pdf error on the measurement properly, it does not help having different central sets only. If we have 40 now, we can have pdf4lhc_30 + errors (33 weights) + nnpdf3.1_pdf_as_hessian (1 central) + mmht14 (1 central) +ct14 (1 central) + abmp16 (1 central). So we can have the pdf uncertainty from pdf4lhc - would be not correct but at least an approximation for most of processes and we can check how wrong it is by checking what is the difference in cross-sections using other central sets. 
Would it work?

**Comment by gpetruc** [comment]
@perrozzi @kdlong  I think for a nanoAOD or user analysis prespective, a hessian with 30-ish components would be better than 100; the latter would multiply by a factor 3 the size in the ntuples (100 floats in full 32 bit precision would be 0.4 kb/event, 30% of nanoAOD budget -> no way), and also the number of templates & nuisances to be filled and put into the datacards, etc.
Also, if increasing the number of items makes the effect of each item individually smaller, it may end up giving a less accurate result depending on the accuracy with which these are propagated and handled (I'm thinking e.g. at when the likelihood is profiled, or the impact of the nuisance terms is determined).

**Comment by klipka** [comment]
sure, but unfortunately each stand-alone modern pdf has more than 50 eigenvectors for the uncertanties and then in addition the variants with different alpha_s and quark masses comes. All have influence on the uncertainty of the cross-section measurement. And we have to take into account different theory treatment and various phenomenological approaches in the PDF determination - that is how a 1000 weights come together. For quite some precision analyses the PDF uncertainty becomes one of the dominant errors, we have to take into account all possible variations.

**Comment by kdlong** [comment]
@klipka @gpetruc first I think we should make sure it's clear what we're discussing. As I see it there are 3 distinct questions for which PDF sets to include.

1) Which PDF set weights should be included in the gridpack generation and the GEN-SIM production
2) Which PDF set weights should be stored in MiniAOD
3) Which PDF set weights should be stored in nanoAOD

For (1), the limit is almost certainly not 30 or 40 weights. I'm not aware of major size constraints, so probably we can include whatever we want subject to the condition that it isn't completely redundant and that there aren't significant issues in the production (e.g. the generator software can handle it). For (2) and (3), the condition should only be that (2) needs to be a subset of (1), and (3) a subset of (2) (I believe...). You could argue that if the list is reduced from ~1000 weights in going from (1) to (2) that it wasn't worth the effort of generating the 1000 weights in the first place, but I think the most critical issue is the one that @gpetruc is addressing, namely to insure that (1) includes a set that is suitable for (3). 

The only set I know of that has ~30 variations is the pdf4lhc_30, though these are MC uncertainties rather than hessian, and the set could also be considered outdated, since it's formed with the 2015 PDF sets. The hessian version of NNPDF3.1 still has ~100, and other main hessian sets have ~50 weights. What's in the current example nanoAOD file? I see nLHEPdfWeight = 50, and I'm not sure how that was obtained.

@bendavid may have more input here.

**Comment by gpetruc** [comment]
sure, i was referring to nanoAOD, for mini O (1000) weights are ok and i
can see the valid usecases for them.

what's now in nano is (the first 50) replicas of nnpdf since that was what
was available in old mc and used by most in 2016.


Il 25 Set 2017 18:05, "Kenneth Long" <notifications@github.com> ha scritto:

@klipka <https://github.com/klipka> @gpetruc <https://github.com/gpetruc>
first I think we should make sure it's clear what we're discussing. As I
see it there are 3 distinct questions for which PDF sets to include.

   1. Which PDF set weights should be included in the gridpack generation
   and the GEN-SIM production
   2. Which PDF set weights should be stored in MiniAOD
   3. Which PDF set weights should be stored in nanoAOD

For (1), the limit is almost certainly not 30 or 40 weights. I'm not aware
of major size constraints, so probably we can include whatever we want
subject to the condition that it isn't completely redundant and that there
aren't significant issues in the production (e.g. the generator software
can handle it). For (2) and (3), the condition should only be that (2)
needs to be a subset of (1), and (3) a subset of (2) (I believe...). You
could argue that if the list is reduced from ~1000 weights in going from
(1) to (2) that it wasn't worth the effort of generating the 1000 weights
in the first place, but I think the most critical issue is the one that
@gpetruc <https://github.com/gpetruc> is addressing, namely to insure that
(1) includes a set that is suitable for (3).

The only set I know of that has ~30 variations is the pdf4lhc_30, though
these are MC uncertainties rather than hessian, and the set could also be
considered outdated, since it's formed with the 2015 PDF sets. The hessian
version of NNPDF3.1 still has ~100, and other main hessian sets have ~50
weights. What's in the current example nanoAOD file? I see nLHEPdfWeight =
50, and I'm not sure how that was obtained.

@bendavid <https://github.com/bendavid> may have more input here.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cms-sw/genproductions/issues/1287#issuecomment-331928672>,
or mute the thread

**Comment by klipka** [comment]
then the plan would be as follows - 
1. the full list of weights to be included. 
2. the ideal case would be keeping all the weigths from 1. if there is a strict limit, we really need to look which analyses are the main consumers of this MC. 
3. nanoAOD: if it is indeed 30 weights, we need to stick to PDF4LHC15. It is the last pdf I would recommend for any precision analysis, since as I explained many times it is an average of 3 PDFs with different assumptions, outdated - only partially since only nnpdf is updated since then. If we want a consistent pdf with errors we need 59 weights - would be CT14nlo with hessian error eigenvectors + alpha_s variations. Or we use ABMP16, which is 31 hessian eigenvectors, but I believe it will raise controversial discussions in CMS.

**Comment by klipka** [comment]
Taking a part of eigenvectors (like 50 from 100 in NNPDF3.1) does not make any sense since these eigenvectors can behave completely different in different kinematics. The uncertainty would be arbitrary.

**Comment by bendavid** [comment]
Yes, fully agreed that taking a subset of the eigenvectors makes no sense.  They are not necessarily ordered by importance (and even if they were this would be highly process and phase-space dependent).

For me it makes sense to include the complete set of variations for the central pdf (for the new production it will be nnpdf 3.1 with 100 hessian variations)

This would be good for everything except detailed pdf studies, and the Higgs group.

If we really think 100 is too much, then in the long term we need to start pushing the PDF groups to produce a sensibly reduced set for their own pdf sets.  (at least for NNPDF it is ~trivially possible)

**Comment by perrozzi** [comment]
LET ME BE CLEAR: THIS THREAD HAS NOTHING TO DO WITH NANOAOD.
WE HAVE ALREADY ENOUGH PROBLEMS WITH THE CREATION OF LHE EVENTS FOR THE MOMENT
PLEASE USE https://github.com/cms-nanoAOD/cmssw/issues/14 AND ONLY THAT FOR NANOAOD
THANKS

**Comment by gpetruc** [comment]
if they're random replicas in random order, ie a sampling of the
uncertainty - as i was told they were - then it makes sense to take a
subset (you just have a worse stat uncertainty on the rms computed from
that)

if they're a hessian, then of course it doesn't.

Giovanni

Il 25 Set 2017 18:23, "klipka" <notifications@github.com> ha scritto:

Taking a part of eigenvectors (like 50 from 100 in NNPDF3.1) does not make
any sense since these eigenvectors can behave completely different in
different kinematics. The uncertainty would be arbitrary.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cms-sw/genproductions/issues/1287#issuecomment-331935387>,
or mute the thread
