### ISSUE TITLE
Slow uscms.org server when using CMSConnect

### ISSUE THREAD

**Issue by kdlong** [cms-sw/genproductions#1481]
@khurtado The one frustration I have with CMSConnect is that the uscms.org server is incredibly slow. If I'm just running a single job that I already have the cards for it's not so bad, but if I want to do any sort of development it's prohibitively slow. Is this only a problem because I'm accessing it from Europe or is the machine always like this? Is there anything that can be done, or any way to submit from another machine?

**Comment by khurtado** [comment]
It's actually not bad  logging in from ND. What's the ping to login.uscms.org  from the machine you are using in Europe?

Since you mention development, I suppose you have issues editing files via emacs, vim, etc... 
We have users from ND at CERN who don't like to use ND machines interactively because of the same reason you are pointing out, (they use emacs, which becomes incredibly slow via ssh) so this could be just a latency-effect.

CMS Connect has a connect-client, so jobs can be submitted remotely via "connect submit" rather than "condor_submit", but I don't think this would work for genproductions due to the master and the fact jobs need to be fetched from the remote machine after they are done.

Also, are you using a CERN machine or your own laptop? You might want to try installing mosh (https://mosh.org) to see if that improves  performance.
